---
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-LeakTracker
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Events::Objects: 0.02
  Devel::Size: 0
  Jifty: 0
  Proc::ProcessTable: 0
version: 0.01
